# Generated by Django 6.0.7 on 2026-07-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('col1_image', models.ImageField(blank=True, null=True, upload_to='columns/')),
                ('col1_text', models.CharField(blank=True, default='', max_length=500)),
                ('col2_image', models.ImageField(blank=True, null=True, upload_to='columns/')),
                ('col2_text', models.CharField(blank=True, default='', max_length=500)),
                ('col3_image', models.ImageField(blank=True, null=True, upload_to='columns/')),
                ('col3_text', models.CharField(blank=True, default='', max_length=500)),
                ('col4_image', models.ImageField(blank=True, null=True, upload_to='columns/')),
                ('col4_text', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
